#!/bin/bash

# Linux
# -----
OS=linux

ARCHITECTURE=host_architecture
PLATFORM=$OS-$ARCHITECTURE
echo "Platform $PLATFORM"
echo ---------------------
./build-platform-on-linux $PLATFORM ../toolchain-$PLATFORM.cmake
echo

# TODO: Cross-platform toolchains are not ready yet.

# ARCHITECTURE=x86_64
# PLATFORM=$OS-$ARCHITECTURE
# echo "Platform $PLATFORM"
# echo ---------------------
# ./build-platform-on-linux $PLATFORM ../--TODO--
# echo

# ARCHITECTURE=x86
# PLATFORM=$OS-$ARCHITECTURE
# echo "Platform $PLATFORM"
# echo ---------------
# ./build-platform-on-linux $PLATFORM ../--TODO--
# echo

# ARCHITECTURE=arm
# PLATFORM=$OS-$ARCHITECTURE
# echo "Platform $PLATFORM"
# echo ------------------
# ./build-platform-on-linux $PLATFORM ../--TODO--
# echo

# ARCHITECTURE=arm64
# PLATFORM=$OS-$ARCHITECTURE
# echo "Platform $PLATFORM"
# echo -----------------
# ./build-platform-on-linux $PLATFORM ../--TODO--
# echo
