#!/bin/bash

# NOTE
# The installation of emsdk is described here: https://emscripten.org/docs/getting_started/index.html

# WebAssembly
# -----------
PLATFORM=webassembly
BUILD_TESTS=OFF
BUILD_SHARED_LIBS=OFF
BUILD_STATIC_LIBS=ON
echo "Platform $PLATFORM"
echo ---------------------
./build-platform-on-linux $PLATFORM $BUILD_TESTS $BUILD_SHARED_LIBS $BUILD_STATIC_LIBS ../../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
echo
