#!/bin/bash
PLATFORM=$1
TOOLCHAIN_FILE=$2
VERSION=$(<version)

BUILD_DIR=cmake-build-$PLATFORM
rm -r -f $BUILD_DIR
mkdir $BUILD_DIR
cd $BUILD_DIR
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE ..
make

../copy-to-output-on-linux . ../output $PLATFORM $VERSION

cd ..
