#!/bin/bash

# Android
# -------
OS=android

ARCHITECTURE=arm64-v8a
PLATFORM=$OS-$ARCHITECTURE
echo "Platform $PLATFORM"
echo --------------------------
./build-platform-on-linux $PLATFORM ../toolchain-$PLATFORM.cmake
echo

ARCHITECTURE=armeabi-v7a
PLATFORM=$OS-$ARCHITECTURE
echo "Platform $PLATFORM"
echo ----------------------------
./build-platform-on-linux $PLATFORM ../toolchain-$PLATFORM.cmake
echo

ARCHITECTURE=x86
PLATFORM=$OS-$ARCHITECTURE
echo "Platform $PLATFORM"
echo --------------------
./build-platform-on-linux $PLATFORM ../toolchain-$PLATFORM.cmake
echo
