set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21) # API level
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK})
#set(CMAKE_ANDROID_STL_TYPE gnustl_static)
#set(CMAKE_ANDROID_STL_TYPE c++_static)